import json

molecule_names={"CO"    : "Carbon Monoxide",
                "HCN"   : "Hydrogen Cyanide",
                "H2S"   : "Hydrogen Sulfide",
                "C2H2"  : "Acetylene",
                "N2O"   : "Nitrous Oxide",
                "N2"    : "Molecular Nitrogen",
                "HO2"   : "Hydroperoxyl Radical",
                "HBr"   : "Hydrogen Bromide",
                "PH3"   : "Phosphine",
                "CH3Br" : "Methyl Bromide",
                "NOp"   : "Nitric Oxide Cation",
                "HCOOH" : "Formic Acid",
                "O2"    : "Molecular Oxygen",
                "SO2"   : "Sulfur Dioxide",
                "NO"    : "Nitric Oxide",
                "O"     : "Oxygen Atom",
                "CH4"   : "Methane",
                "COF2"  : "Carbonyl Fluoride",
                "H2CO"  : "Formaldehyde",
                "C2H4"  : "Ethylene",
                "C2H6"  : "Ethane",
                "CS"    : "Carbon Monosulfide",
                "NH3"   : "Ammonia",
                "OH"    : "Hydroxyl Radical",
                "CO2"   : "Carbon Dioxide",
                "C4H2"  : "Diacetylene",
                "HC3N"  : "Cyanoacetylene",
                "CH3Cl" : "Methyl Chloride",
                "OCS"   : "Carbonyl Sulfide",
                "CH3OH" : "Methanol",
                "ClO"   : "Chlorine Monoxide",
                "H2O2"  : "Hydrogen Peroxide",
                "HCl"   : "Hydrogen Chloride",
                "H2O"   : "Water",
                "CH3CN" : "Methyl Cyanide",
                "HOCl"  : "Hypochlorous Acid",
                "HOBr"  : "Hypobromous Acid",
                "NO2"   : "Nitrogen Dioxide",
                "HNO3"  : "Nitric Acid",
                "HI"    : "Hydrogen Iodide",
                "SO3"   : "Sulfur trioxide",
                "HF"    : "Hydrogen Fluoride",
                "H2"    : "Molecular Hydrogen",
                "O3"    : "Ozone"}

    
config = json.dump(molecule_names, open("molecule_names.txt", "w"))

